### ISSUE TITLE
Lightdm not setup properly. You must set your default desktop with lightdm prior to remastering

### ISSUE THREAD

**Issue by mishmosh21** [ch1x0r/LinuxRespin#16]
How to fix on Ubuntu Mate 16.04?

**Comment by clessley** [comment]
@mishmosh21 

`gksu pluma /usr/bin/respin`

Comment out the line 245 of beginning with 

`[ “grep lightdm /etc/X11/default-display-manager” != “” ]`

Reference Remastersystem 14.04: [http://www.nemotos.net/?p=827 ](http://www.nemotos.net/?p=827)

I'm at 3% complete, will delete this comment if the restore fails in virtual machine test.

**Comment by clessley** [comment]
@mishmosh21 

Check out this, might be the winning combination? Try on your end, I'll due the same with my little amd64 netbook and report back.

**Comment by ch1x0r** [comment]
There are a couple of solutions for this - 1. Change your default to lightdm - that might not be a feasible solution for everyone. What if you don't want lightdm...
2. Solution above but not working with output of iso. 
3. Change code myself

I received the same error, myself - wherein I have not changed the code or anything in respin...
So, must go back and change the code myself since I don't think the ubuntu team is active anymore.

**Comment by ch1x0r** [comment]
sems to be working fine. got a warning because I am usuing minty fresh - and that declares mdm.
The idea here by using trisquel is to create a fully free distro creating software that creates a fully free distro/ custom/ backup of trisquel - FULLY FREE! :D <3

**Comment by ch1x0r** [comment]
Update: the custom.iso is 1.2 gb in size.  Going to test in a 
![screenshot from 2017-02-26 01 57 28](https://cloud.githubusercontent.com/assets/4945600/23345364/7268c1fc-fc4a-11e6-988f-45c90e1af18a.png)
![screenshot from 2017-02-26 01 56 55](https://cloud.githubusercontent.com/assets/4945600/23345363/7268c67a-fc4a-11e6-8d88-9aad2502ad47.png)

vm.

**Comment by clessley** [comment]
@ch1x0r Lightdm is the default (unless I am mistaken) in Ubuntu MATE so the need to set it as default(?).

How'd the VM restore test go with Trisquel and MDM?

**Comment by ch1x0r** [comment]
I need to put in nextcloud on the server to make sure I can get these files easier. Using vbox. I guess I can just install guest addition... Almost there.

**Comment by ch1x0r** [comment]
Alright - so I made a shared folder to finish testing in virtual box. The test turned out fine except... 1 thing I remember the Ubuntu team discussed as an issue. 
LIVE CD - Requires login. Sergio has this solution I believe. I never had this issue with debian based distros. So, I need to get with him on the ports to trisquel and mint - the ubuntu ones and then, the login on live will be solved. 
Installed iso - this maintained the password set during the iso install process

**Comment by padrino121** [comment]
Found this because of a similar issue, I have a system without X windows (console only) I was trying to use this with and it's tossing out this error. Is there formal support for systems with no GUI?

**Comment by ch1x0r** [comment]
This is very interesting. I never considered this option. Not everyone has a window manager or GUI at all - or the X-Window-SYSTEM.... Hmmm... Let me think about how to approach that and make a version. most useful idea.

**Comment by clessley** [comment]
@padrino121  @ch1x0r This would be quite helpful. I could theorize using it to export an droplet from Digital Ocean. Its been one of their (unanswered) feature requests for ages; the ability to download a VM from the cloud directly but as an .iso file.

**Comment by Lew-Rockwell-Fan** [comment]
FWIW, maybe relevant, maybe not:
My main system is based on Ubuntu Xenial 16.04 LTS, built from the mini.iso. I DO use X and the window manager Openbox, but do NOT use any display manager (such as lightdm). When I want X, I start it with startx. I know I've seen error messages about lightdm in the past, but I just searched the log of the last Respin run & didn't find any. Mostly everything works fine anyway. I do have get one oddity I suspect may derive from not having lightdm installed - on the respun live system the hostname gets set to my username. That created some problems with sudo because I changed Ubuntu's insane default in /etc/sudoers of
`ALL=(ALL:ALL) ALL`
so that sudo can only be done from specified hosts. But I fixed that by adding including the username as an additional allowed hostname. BTW, this illustrates another good reason to enable `su` by setting root's password. That way, you can even fix things like this on a live system.

**Comment by clessley** [comment]
@ch1x0r I know you no longer support Ubuntu users per #36 but I wanted to add here for MATE users that 16.04.2+ works using the other repo method but I still had to comment the line out for lightDM even though its the default display. Everything else still great. Happy imaging!

**Comment by ch1x0r** [comment]
@clessley This is really a known thing, but maybe not for Ubuntu users. 
I hear many fear the command line! Haha.
There is an Ubuntu developer on this project. His name is Chamuco.
So, if you need support or have suggestions, his project is on launchpad along with all accompanying files. 
Now, I'm focusing on Trisquel because a privacy lab at an Ivy league was asking about respin... and I'm all over that! Sorry Ubuntu users... you are on your own.
That being said, I think Ubuntu has some backup tools you could use.
Maybe something GUI based.
The problem here is I actually had some Ubuntu users demanding I make a server edition.
Uh... yea. 
And the reason remastersys was abandoned and we picked up the project was because the dev was tired of being barraged by users requesting features.
It's open.
Make some!
The Ubuntu community has not even contributed one single line of code to the Ubuntu version.
However, for the Debian version, someone wrote a front end, people did testing, they contributed ideas and code for opitmization.
The thing is ... Ubuntu is NOT a community distro. It's a business. You may as well use Winblows.

**Comment by clessley** [comment]
For those who don't know how to search in the issues or otherwise: https://launchpad.net/~sergiomejia666/+archive/ubuntu/respin

@ch1x0r Thanks for your help in the past, I appreciate your work.
