### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by javierloharces** [ch1x0r/LinuxRespin#25]
Is it possible to install a GUI for LinuxRespin in Ubuntu? Thank you :)

**Comment by ch1x0r** [comment]
Yes. I just need time to push that file. Let me see - I have monday off!

**Comment by Lew-Rockwell-Fan** [comment]
Here ya go, a gxmessage based GUI wrapper for Ubuntu Respin.  Maybe it  will be useful until an official one comes along. The attached file is actually a tar, not a zip, but I had to rename it for github to take it. So  just rename it, taking  off the spurious ".zip", and extract it (depending on your extraction software, you may not even NEED to rename it) onto a native extN filesystem. Other filesytem types may work but if you extract to a FAT-n or to an NTFS you're likely to get permission problems. Inside you find a bash script and a directory containing 3 more files. 2 of those are also bash scripts and the other is a desktop file. I haven't tested this 7 ways from Sunday, but I have 2 ways from Monday, and it works. Well, mostly. I'm not sure the desktop file works, but I can't test that part because my debian-menu menu isn't working quite right and I haven't spent the time to figure out why because I mostly use the Openbox static menu, or a terminal or a runbox. The scripts are all short and easy to eyeball. An uninstaller is built in. If the desktop doesn't work, you can launch it by typing `respin_gx` in a runbox or `nohup respin_gx &` in a terminal. If the desktop file works the way I think it should, it should just show on most adaptive menus, and I'd  be curious to know if it DOES work that way for anyone  who tries it. Or if it doesn't maybe you can tell be what I did wrong on it. This doesn't support the [cdfs|iso] options, nor specifying a name for the iso other than what's in your /etc/respin.conf file, although, you can easily add those options if you need them. When an official GUI comes out, this won't interfere with it, since it just calls the command line program.
[respin_gx_files_and_installer.tar.zip](https://github.com/ch1x0r/LinuxRespin/files/1079929/respin_gx_files_and_installer.tar.zip)
